name: CI

on:
  push:
    branches: [ main, 3.3 ]
  pull_request:
    branches: [ main, 3.3 ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Debezium Core
        run: |
          git clone https://github.com/debezium/debezium.git
          cd debezium
          ./mvnw clean install -DskipTests -pl :debezium-parent,:debezium-bom,:debezium-core,:debezium-embedded,:debezium-storage-file,:debezium-storage-kafka,:debezium-ide-configs,:debezium-checkstyle,:debezium-revapi
      - name: Run unit tests
        run: ./mvnw test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Start Docker
        run: sudo systemctl start docker
      - name: Build Debezium Core
        run: |
          git clone https://github.com/debezium/debezium.git
          cd debezium
          ./mvnw clean install -DskipTests -pl :debezium-parent,:debezium-bom,:debezium-core,:debezium-embedded,:debezium-storage-file,:debezium-storage-kafka,:debezium-ide-configs,:debezium-checkstyle,:debezium-revapi
      - name: Run integration tests
        run: ./mvnw verify -DskipUnitTests

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Debezium Core
        run: |
          git clone https://github.com/debezium/debezium.git
          cd debezium
          ./mvnw clean install -DskipTests -pl :debezium-parent,:debezium-bom,:debezium-core,:debezium-embedded,:debezium-storage-file,:debezium-storage-kafka,:debezium-ide-configs,:debezium-checkstyle,:debezium-revapi
      - name: Run checkstyle
        run: ./mvnw checkstyle:check 