#
# Copyright Debezium Authors
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#
# Cross CI workflow is triggered on a `pull_request` event.
# It builds the Debezium core before building the CockroachDB connector basing on either the `main` branch or the `pull_request` branch.
# If a `pull_request` with same branch name is present in the Debezium's upstream core repository, then the core build of this `pull_request`
# will be based on `pull_request` branch of user's Debezium core repository.
# Otherwise the core build of this `pull_request` will be based on the `main` branch of Debezium's upstream core repository.

name: Cross Maven CI

on:
  pull_request:
    branches:
      - main
      - 3.*
      - 4.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core repository
        uses: actions/checkout@v4
        with:
          repository: debezium/debezium
          ref: main
          path: core
      - name: Checkout CockroachDB connector
        uses: actions/checkout@v4
        with:
          path: cockroachdb
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build core
        run: ./core/mvnw clean install -B -ntp -f core/pom.xml -DskipTests
      - name: Build CockroachDB connector
        run: ./cockroachdb/mvnw clean install -B -ntp -f cockroachdb/pom.xml -DskipTests 