#
# Copyright Debezium Authors
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#
name: Maven CI

on:
  push:
    branches:
      - main
      - 3.*
      - 4.*
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - 3.*
      - 4.*
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build-core:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key-generator.outputs.cache-key }}
    steps:
      - name: Checkout Debezium Core
        uses: actions/checkout@v4
        with:
          repository: debezium/debezium
          ref: main
          path: core

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate Cache Key
        id: cache-key-generator
        run: echo "cache-key=${{ runner.os }}-m2-${{ hashFiles('core/**/pom.xml','core/**/*.java') }}" >> "$GITHUB_OUTPUT"

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ steps.cache-key-generator.outputs.cache-key }}
          restore-keys: ${{ steps.cache-key-generator.outputs.cache-key }}

      - name: Build Debezium Core
        run: >
          ./core/mvnw clean install -B -ntp -f core/pom.xml
          -pl debezium-assembly-descriptors,debezium-bom,debezium-core,debezium-embedded,debezium-connector-jdbc,:debezium-storage-file,:debezium-storage-kafka,:debezium-ide-configs,:debezium-checkstyle,:debezium-revapi
          -am
          -DskipTests=true
          -DskipITs=true
          -Dcheckstyle.skip=true
          -Dformat.skip=true
          -Drevapi.skip=true
          -Dhttp.keepAlive=false
          -Dmaven.wagon.http.pool=false
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

  unit-test:
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout CockroachDB Connector
        uses: actions/checkout@v4
        with:
          path: cockroachdb

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ needs.build-core.outputs.cache-key }}
          restore-keys: ${{ needs.build-core.outputs.cache-key }}

      - name: Run unit tests only
        run: ./cockroachdb/mvnw clean test -DskipITs=true -f cockroachdb/pom.xml
        env:
          MAVEN_OPTS: -Xmx2g

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-results
          path: cockroachdb/target/surefire-reports/
          retention-days: 7

  integration-test:
    runs-on: ubuntu-latest
    needs: [build-core, unit-test]
    steps:
      - name: Checkout CockroachDB Connector
        uses: actions/checkout@v4
        with:
          path: cockroachdb

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ needs.build-core.outputs.cache-key }}
          restore-keys: ${{ needs.build-core.outputs.cache-key }}

      - name: Start Docker daemon
        run: sudo systemctl start docker

      - name: Run integration tests
        run: ./cockroachdb/mvnw test -Dtest="*IT" -DfailIfNoTests=false -f cockroachdb/pom.xml
        env:
          MAVEN_OPTS: -Xmx2g

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: cockroachdb/target/failsafe-reports/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: [build-core, unit-test, integration-test]
    steps:
      - name: Checkout CockroachDB Connector
        uses: actions/checkout@v4
        with:
          path: cockroachdb

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ needs.build-core.outputs.cache-key }}
          restore-keys: ${{ needs.build-core.outputs.cache-key }}

      - name: Build artifacts
        run: ./cockroachdb/mvnw clean package -DskipTests -f cockroachdb/pom.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: cockroachdb/target/*.jar
          retention-days: 30

  checkstyle:
    runs-on: ubuntu-latest
    needs: [build-core, unit-test]
    steps:
      - name: Checkout CockroachDB Connector
        uses: actions/checkout@v4
        with:
          path: cockroachdb

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven Repository
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ needs.build-core.outputs.cache-key }}
          restore-keys: ${{ needs.build-core.outputs.cache-key }}

      - name: Run checkstyle
        run: ./cockroachdb/mvnw checkstyle:check -f cockroachdb/pom.xml 